### ISSUE TITLE
Sidebar colour scheme unreadable on Monospace (light)

### ISSUE THREAD

**Issue by turkeyphant** [typora/typora-monospace-theme#3]
![image](https://user-images.githubusercontent.com/8129583/61714317-7302d600-ad52-11e9-9238-21bfdf75012f.png)

It seems to be using a dark background instead of a light one.

**Comment by turkeyphant** [comment]
If you change`--side-bar-bg-color` to a light colour there are still issues with the highlight background colour and very light grey text.

**Comment by abnerlee** [comment]
should be fixed already
