### ISSUE TITLE
How to see options in sidebar footer.

### ISSUE THREAD

**Issue by kiramclean** [typora/typora-monospace-theme#6]
The side bar options are invisible unless hovered over on the light theme. I'm using the latest version of Typora (0.9.9.33.2 (4442)) on macOS.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/11531673/82847791-161a0400-9ebe-11ea-8d9c-77144933b940.png">

On hover:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/11531673/82847820-4366b200-9ebe-11ea-813c-925d5b08f09a.png">

I feel like it should be simple to fix, I just don't know which class to use. Is there a way to inspect the source of the UI to be able to find out how to fix it? Or would anyone happen to know which css rule I need to add to fix it?

Thanks for the great theme, I really like it.

**Comment by abnerlee** [comment]
Which theme and which macOS version are you using?

**Comment by kiramclean** [comment]
Hi there, I'm on macOS Catalina (10.15.5 (19F96))

**Comment by abnerlee** [comment]
should be fixed already
